import type { Module } from '../types'

export const modules: Module[] = [
  {
    id: 'intro',
    title: 'Введение',
    description: 'Что такое DevOps и с чего начать путь',
    icon: 'Rocket',
    order: 0,
  },
  {
    id: 'fundamentals',
    title: 'Основы',
    description: 'Linux, сети, Git и Bash — фундамент DevOps',
    icon: 'Terminal',
    order: 1,
  },
  {
    id: 'containers',
    title: 'Контейнеры',
    description: 'Docker и Docker Compose',
    icon: 'Box',
    order: 2,
  },
  {
    id: 'orchestration',
    title: 'Оркестрация',
    description: 'Kubernetes и Helm',
    icon: 'Layers',
    order: 3,
  },
  {
    id: 'cicd',
    title: 'CI/CD',
    description: 'Автоматизация сборки и доставки',
    icon: 'GitBranch',
    order: 4,
  },
  {
    id: 'iac',
    title: 'Infrastructure as Code',
    description: 'Terraform и Ansible',
    icon: 'FileCode',
    order: 5,
  },
  {
    id: 'cloud',
    title: 'Облака',
    description: 'AWS и облачная инфраструктура',
    icon: 'Cloud',
    order: 6,
  },
  {
    id: 'observability',
    title: 'Наблюдаемость',
    description: 'Мониторинг, логи и алерты',
    icon: 'Activity',
    order: 7,
  },
  {
    id: 'security',
    title: 'Безопасность',
    description: 'DevSecOps и защита инфраструктуры',
    icon: 'Shield',
    order: 8,
  },
  {
    id: 'career',
    title: 'Карьера',
    description: 'Портфолио, сертификации и собеседования',
    icon: 'GraduationCap',
    order: 9,
  },
  {
    id: 'sysadmin',
    title: 'Системное администрирование',
    description: 'Windows Server, Active Directory, GPO и бэкапы',
    icon: 'Server',
    order: 10,
  },
  {
    id: 'office-network',
    title: 'Офисные сети',
    description: 'Проектирование, VLAN, DHCP/DNS и Wi‑Fi',
    icon: 'Network',
    order: 11,
  },
  {
    id: 'omada',
    title: 'TP-Link Omada',
    description: 'Controller, switches, EAP и VPN',
    icon: 'Wifi',
    order: 12,
  },
  {
    id: 'fortinet',
    title: 'Fortinet',
    description: 'FortiGate, firewall, VPN и эксплуатация',
    icon: 'ShieldCheck',
    order: 13,
  },
  {
    id: 'it-support',
    title: 'IT Support',
    description: 'Helpdesk, рабочие станции и playbooks',
    icon: 'Headphones',
    order: 14,
  },
]
