import type { QuizQuestion } from '../types'

export const officeItQuizzes: Record<string, QuizQuestion[]> = {
  'windows-server-basics': [
    { question: 'Какой инструмент — центральная консоль управления ролями Windows Server?', options: ['Server Manager', 'Device Manager', 'Task Scheduler', 'Regedit'], answer: 'Server Manager' },
    { question: 'Почему Domain Controller не должен получать IP через DHCP?', options: ['Стабильный адрес критичен для DNS и AD', 'DHCP запрещён Microsoft', 'Это только рекомендация для Wi‑Fi'], answer: 'Стабильный адрес критичен для DNS и AD' },
    { question: 'Какая edition Windows Server подходит типичному офису с несколькими VM?', options: ['Standard', 'Datacenter', 'Home', 'Embedded'], answer: 'Standard' },
    { question: 'Чем управляют службы Windows из командной строки?', answer: 'Get-Service, Start-Service, Stop-Service, Restart-Service (PowerShell) или sc.exe' },
    { question: 'Почему RDP не следует открывать напрямую в интернет?', options: ['Высокий риск brute-force и эксплойтов', 'RDP не работает через NAT', 'Требуется только UDP'], answer: 'Высокий риск brute-force и эксплойтов' },
    { question: 'Hyper-V на Windows Server используется для:', options: ['Виртуализации серверов и lab', 'Только контейнеров Docker', 'Только файлового сервера'], answer: 'Виртуализации серверов и lab' },
    { question: 'WSUS на Windows Server нужен для:', options: ['Централизованного управления обновлениями', 'Только DNS', 'Только VPN', 'Только печати'], answer: 'Централизованного управления обновлениями' },
    { question: 'Windows Server Core выбирают потому что:', options: ['Меньше поверхность атаки и патчей', 'Нет поддержки AD', 'Нельзя использовать RDP', 'Только для Linux VM'], answer: 'Меньше поверхность атаки и патчей', explanation: 'Core — без GUI, меньше компонентов для обслуживания и атак.' },
    { question: 'Команда переименования Windows Server в PowerShell:', answer: 'Rename-Computer -NewName "имя" -Restart' },
    { question: 'Роль файлового сервера SMB на Windows Server обеспечивает:', options: ['Общий доступ к папкам в домене', 'Только DHCP', 'Только Wi‑Fi', 'Только VPN'], answer: 'Общий доступ к папкам в домене' },
  ],
  'active-directory': [
    { question: 'Что такое OU в Active Directory?', options: ['Контейнер для делегирования и GPO', 'Тип группы безопасности', 'DNS-зона'], answer: 'Контейнер для делегирования и GPO' },
    { question: 'Какой протокол аутентификации использует AD по умолчанию?', options: ['Kerberos', 'NTLM only', 'LDAP plain text'], answer: 'Kerberos' },
    { question: 'Сколько минимум DC рекомендуется в production?', options: ['2', '1', '5'], answer: '2' },
    { question: 'AGDLP расшифровывается как:', answer: 'Account → Global group → Domain Local group → Permission' },
    { question: 'Где хранится AD-интегрированная DNS-зона?', options: ['В Active Directory', 'Только в hosts файле', 'На роутере'], answer: 'В Active Directory' },
    { question: 'Команда проверки здоровья DC:', options: ['dcdiag', 'ipconfig', 'docker ps'], answer: 'dcdiag' },
    { question: 'Global Security Group в AD используют для:', options: ['Сбора пользователей по ролям/отделам', 'Прямого назначения NTFS прав', 'Хранения DNS-зон', 'Публикации принтеров только'], answer: 'Сбора пользователей по ролям/отделам', explanation: 'По AGDLP пользователей добавляют в Global, права — через Domain Local.' },
    { question: 'Лес (Forest) в AD — это:', options: ['Граница безопасности и схемы', 'Один OU', 'Только DNS-зона', 'Группа принтеров'], answer: 'Граница безопасности и схемы' },
    { question: 'Утилита для поиска источника блокировки учётной записи:', answer: 'LockoutStatus.exe или Get-ADUser / Event Viewer (ID 4740)' },
    { question: 'Репликация AD между DC использует протокол:', options: ['RPC / SMTP (для межсайтовой)', 'Только HTTP', 'Только FTP', 'Только SNMP'], answer: 'RPC / SMTP (для межсайтовой)' },
  ],
  'gpo-user-management': [
    { question: 'Что означает LSDOU в Group Policy?', options: ['Local, Site, Domain, OU — порядок применения', 'Linux, Server, Domain, User', 'Logon, Startup, Domain, OU'], answer: 'Local, Site, Domain, OU — порядок применения' },
    { question: 'GPO Preferences используются для:', options: ['Drive maps, registry, shortcuts без ADMX', 'Только паролей', 'Только BitLocker'], answer: 'Drive maps, registry, shortcuts без ADMX' },
    { question: 'Первая операция при offboarding сотрудника:', options: ['Disable AD account', 'Delete AD account', 'Format PC'], answer: 'Disable AD account' },
    { question: 'Команда принудительного обновления GPO на клиенте:', answer: 'gpupdate /force' },
    { question: 'Где НЕ следует хранить пароли в GPO?', options: ['GPP Scheduled Tasks с embedded creds', 'GPO Password Policy', 'GPO Screensaver lock'], answer: 'GPP Scheduled Tasks с embedded creds' },
    { question: 'Computer Configuration применяется:', options: ['При загрузке компьютера', 'Только при logout', 'Только на DC'], answer: 'При загрузке компьютера' },
    { question: 'Item-Level Targeting в GPO Preferences позволяет:', options: ['Применять настройку по условию (OU, группа, IP)', 'Шифровать GPO', 'Удалять AD-объекты', 'Менять схему леса'], answer: 'Применять настройку по условию (OU, группа, IP)' },
    { question: 'gpresult /r на клиенте показывает:', options: ['Какие GPO применены', 'Список всех DC', 'Только MAC-адрес', 'Только DHCP lease'], answer: 'Какие GPO применены' },
    { question: 'Команда просмотра применённых GPO с HTML-отчётом:', answer: 'gpresult /h report.html' },
    { question: 'Loopback Processing в GPO нужен когда:', options: ['Нужны user settings независимо от физического места ПК', 'Отключить все GPO', 'Только для DC', 'Только для принтеров'], answer: 'Нужны user settings независимо от физического места ПК', explanation: 'Режим Merge или Replace — для терминалов, kiosk, lab.' },
  ],
  'backups-disaster-recovery': [
    { question: 'Правило 3-2-1 в бэкапах:', options: ['3 копии, 2 носителя, 1 offsite', '3 сервера, 2 диска, 1 tape', '3 раза в день'], answer: '3 копии, 2 носителя, 1 offsite' },
    { question: 'RPO означает:', options: ['Допустимая потеря данных по времени', 'Время восстановления сервиса', 'Количество реплик'], answer: 'Допустимая потеря данных по времени' },
    { question: 'System State backup критичен для:', options: ['Domain Controller', 'Только принтера', 'Только Wi‑Fi'], answer: 'Domain Controller' },
    { question: 'Veeam чаще используют для:', options: ['Image-level backup VM', 'Только DNS', 'Только GPO'], answer: 'Image-level backup VM' },
    { question: 'Первый приоритет восстановления после катастрофы:', options: ['AD / DNS', 'Принтеры', 'Guest Wi‑Fi'], answer: 'AD / DNS' },
    { question: 'Immutable backup защищает от:', options: ['Ransomware', 'Медленного интернета', 'VLAN misconfiguration'], answer: 'Ransomware' },
    { question: 'RTO (Recovery Time Objective) — это:', options: ['Допустимое время простоя сервиса', 'Допустимая потеря данных', 'Количество копий бэкапа', 'Срок хранения ленты'], answer: 'Допустимое время простоя сервиса', explanation: 'RPO — сколько данных можно потерять; RTO — как быстро восстановить работу.' },
    { question: 'Тест восстановления (restore drill) нужен чтобы:', options: ['Убедиться что бэкапы реально работают', 'Ускорить интернет', 'Обновить GPO', 'Сменить VLAN'], answer: 'Убедиться что бэкапы реально работают' },
    { question: 'Первый шаг при восстановлении DC из бэкапа:', answer: 'Загрузка в Directory Services Restore Mode (DSRM) или восстановление System State' },
    { question: 'Offsite-копия бэкапа обычно хранится:', options: ['В другом здании/облаке, отдельно от production', 'На том же NAS что production', 'Только на рабочем столе админа', 'В Guest VLAN'], answer: 'В другом здании/облаке, отдельно от production' },
  ],
  'office-network-design': [
    { question: 'Типовое место firewall в офисной сети:', options: ['Между ISP и внутренней сетью', 'За каждым ПК', 'Только в Wi‑Fi'], answer: 'Между ISP и внутренней сетью' },
    { question: 'VLAN Guest обычно должен:', options: ['Иметь доступ только в интернет', 'Видеть серверы AD', 'Быть без DHCP'], answer: 'Иметь доступ только в интернет' },
    { question: 'Зачем PoE switch в офисе?', options: ['Питание AP и IP-телефонов по Ethernet', 'Только быстрее интернет', 'Только для серверов'], answer: 'Питание AP и IP-телефонов по Ethernet' },
    { question: 'IPAM нужен для:', options: ['Учёта IP-адресов и подсетей', 'Только Wi‑Fi паролей', 'Только VPN'], answer: 'Учёта IP-адресов и подсетей' },
    { question: 'Dual WAN даёт:', options: ['Резервирование интернет-канала', 'Бесплатный интернет', 'Автоматический AD'], answer: 'Резервирование интернет-канала' },
    { question: 'Маркировка патч-кордов нужна для:', options: ['Быстрой диагностики при отказе', 'Красоты', 'Снижения PoE'], answer: 'Быстрой диагностики при отказе' },
    { question: 'DMZ в офисной сети используют для:', options: ['Публикации сервисов с ограниченным доступом извне', 'Хранения AD', 'Guest Wi‑Fi без firewall', 'Только принтеров'], answer: 'Публикации сервисов с ограниченным доступом извне' },
    { question: 'Core switch в трёхуровневой модели — это:', options: ['Центральный L3/L2 узел агрегации', 'Только Wi‑Fi контроллер', 'Модем ISP', 'Принтерный сервер'], answer: 'Центральный L3/L2 узел агрегации' },
    { question: 'Главная цель сегментации сети в офисе:', answer: 'Ограничение blast radius — изоляция гостей, IoT и критичных систем' },
    { question: 'Стандарт структурированной кабельной системы в офисе:', options: ['TIA/EIA-568', 'ISO 9001', 'PCI DSS', 'HIPAA only'], answer: 'TIA/EIA-568' },
  ],
  'vlan-switching': [
    { question: '802.1Q добавляет в кадр:', options: ['VLAN tag', 'IP address', 'MAC only'], answer: 'VLAN tag' },
    { question: 'Trunk порт используется для:', options: ['Передачи нескольких VLAN tagged', 'Одного ПК', 'Только management'], answer: 'Передачи нескольких VLAN tagged' },
    { question: 'STP предотвращает:', options: ['Петли L2', 'DDoS', 'Virus'], answer: 'Петли L2' },
    { question: 'Inter-VLAN routing в SMB чаще на:', options: ['Firewall / L3 gateway', 'Принтере', 'Каждом ПК'], answer: 'Firewall / L3 gateway' },
    { question: 'BPDU Guard включают на:', options: ['Access портах', 'Только WAN', 'Только серверах'], answer: 'Access портах' },
    { question: 'LAG (LACP) даёт:', options: ['Объединение линков для bandwidth и redundancy', 'Только Wi‑Fi', 'Только VLAN 1'], answer: 'Объединение линков для bandwidth и redundancy' },
    { question: 'Native VLAN на trunk-порту — это:', options: ['Untagged VLAN для кадров без 802.1Q tag', 'Самый защищённый VLAN', 'Только management', 'VLAN для принтеров'], answer: 'Untagged VLAN для кадров без 802.1Q tag', explanation: 'Native VLAN на обоих концах trunk должен совпадать — иначе утечки и петли.' },
    { question: 'Voice VLAN (802.1p) выделяют для:', options: ['Приоритета IP-телефонии', 'Только гостей', 'Только серверов AD', 'Отключения PoE'], answer: 'Приоритета IP-телефонии' },
    { question: 'Команда перевода порта в access mode (типичный Cisco CLI):', answer: 'switchport mode access' },
    { question: 'Root bridge в STP выбирается по:', options: ['Наименьшему Bridge Priority + MAC', 'Наибольшему IP', 'Случайно', 'Количеству PoE портов'], answer: 'Наименьшему Bridge Priority + MAC' },
  ],
  'office-dhcp-dns': [
    { question: 'Два активных DHCP на одном scope вызывают:', options: ['Конфликты IP', 'Быстрый интернет', 'Автоматический AD'], answer: 'Конфликты IP' },
    { question: 'DHCP Relay нужен когда:', options: ['DHCP сервер в другом VLAN', 'Нет интернета', 'Только Wi‑Fi'], answer: 'DHCP сервер в другом VLAN' },
    { question: 'Клиенты домена AD должны использовать DNS:', options: ['Domain Controller', 'Только 8.8.8.8', 'Только роутер ISP'], answer: 'Domain Controller' },
    { question: '«Интернет есть, домен нет» — чаще проблема:', options: ['Клиент не использует DC DNS', 'Сломан принтер', 'Нет PoE'], answer: 'Клиент не использует DC DNS' },
    { question: 'DHCP reservation привязывает IP к:', options: ['MAC-адресу', 'Имени пользователя', 'VLAN только'], answer: 'MAC-адресу' },
    { question: 'SRV запись _ldap._tcp нужна для:', options: ['Поиска Domain Controller', 'Почты', 'Печати'], answer: 'Поиска Domain Controller' },
    { question: 'TTL в DNS-записи определяет:', options: ['Время кэширования ответа клиентом', 'Скорость интернета', 'DHCP lease', 'VLAN ID'], answer: 'Время кэширования ответа клиентом' },
    { question: 'Типичный DHCP lease time в офисе:', options: ['8–24 часа', '5 секунд', '365 дней', 'Без срока (вечный)'], answer: '8–24 часа' },
    { question: 'Команда сброса DNS-кэша на Windows-клиенте:', answer: 'ipconfig /flushdns' },
    { question: 'Dynamic DNS update в AD позволяет:', options: ['Клиентам регистрировать A/AAAA записи в зоне', 'Удалять DC', 'Менять VLAN', 'Отключать Kerberos'], answer: 'Клиентам регистрировать A/AAAA записи в зоне', explanation: 'Без secure DDNS старые записи накапливаются — нужна очистка и scavenging.' },
  ],
  'office-wifi': [
    { question: 'WPA3-Enterprise использует:', options: ['802.1X / RADIUS', 'Один общий пароль для всех', 'Открытую сеть'], answer: '802.1X / RADIUS' },
    { question: 'Guest Wi‑Fi должен иметь:', options: ['Client isolation и доступ только в WAN', 'Доступ к AD', 'Тот же VLAN что Corp'], answer: 'Client isolation и доступ только в WAN' },
    { question: 'RADIUS в Windows офисе часто на:', options: ['NPS', 'FortiGate only', 'Принтере'], answer: 'NPS' },
    { question: '5 GHz предпочтителен потому что:', options: ['Больше каналов, меньше помех', 'Дальше пробивает бетон', 'Не нужен PoE'], answer: 'Больше каналов, меньше помех' },
    { question: 'Fast roaming (802.11r) уменьшает:', options: ['Разрывы при ходьбе между AP', 'Стоимость лицензий', 'Нужду в DNS'], answer: 'Разрывы при ходьбе между AP' },
    { question: 'Скрытие SSID:', options: ['Не является реальной защитой', 'Заменяет WPA3', 'Блокирует гостей'], answer: 'Не является реальной защитой' },
    { question: 'Неперекрывающиеся каналы 2.4 GHz:', options: ['1, 6, 11', '1, 2, 3', '5, 10, 15', 'Только канал 14'], answer: '1, 6, 11' },
    { question: 'WPA3-Personal улучшает по сравнению с WPA2:', options: ['Защиту от offline brute-force (SAE)', 'Дальность сигнала', 'PoE budget', 'Скорость DNS'], answer: 'Защиту от offline brute-force (SAE)' },
    { question: 'Инструмент для Wi‑Fi site survey в офисе:', answer: 'Ekahau, NetSpot, inSSIDer или встроенный survey в контроллере' },
    { question: 'Channel bonding 80 MHz на 5 GHz даёт:', options: ['Больше throughput, но меньше свободных каналов', 'Только 2.4 GHz', 'Отключение PoE', 'Автоматический AD join'], answer: 'Больше throughput, но меньше свободных каналов', explanation: 'В плотных офисах часто лучше 20/40 MHz для меньших помех.' },
  ],
  'omada-fundamentals': [
    { question: 'Omada — это SDN платформа от:', options: ['TP-Link', 'Cisco', 'Fortinet'], answer: 'TP-Link' },
    { question: 'Варианты Omada Controller:', options: ['Cloud, Software, Hardware OC200', 'Только облако', 'Только CLI'], answer: 'Cloud, Software, Hardware OC200' },
    { question: 'Adoption в Omada — это:', options: ['Подключение устройства к controller', 'Удаление VLAN', 'Форматирование AP'], answer: 'Подключение устройства к controller' },
    { question: 'Порядок firmware update:', options: ['Controller → switches → AP', 'AP → controller', 'Случайный'], answer: 'Controller → switches → AP' },
    { question: 'Omada Gateway в топологии стоит:', options: ['Между Internet и LAN', 'Только в Wi‑Fi', 'За каждым ПК'], answer: 'Между Internet и LAN' },
    { question: 'Backup конфига controller нужен:', options: ['Регулярно, перед изменениями', 'Никогда', 'Только при смене ISP'], answer: 'Регулярно, перед изменениями' },
    { question: 'Omada Discovery Utility нужна для:', options: ['Поиска устройств до adoption', 'Удаления VLAN', 'Настройки AD', 'Печати'], answer: 'Поиска устройств до adoption' },
    { question: 'Site в Omada Controller — это:', options: ['Логическая группа устройств одной локации', 'Только один AP', 'DNS-зона', 'VPN-туннель'], answer: 'Логическая группа устройств одной локации', explanation: 'Organization может содержать несколько Site для филиалов.' },
    { question: 'Порт HTTPS Omada Software Controller по умолчанию:', answer: '8043 (или 443 при reverse proxy)' },
    { question: 'Inform URL на устройстве Omada указывает:', options: ['Адрес controller для adoption', 'DNS ISP', 'Принтер', 'RADIUS только'], answer: 'Адрес controller для adoption' },
  ],
  'omada-switches-vlans': [
    { question: 'Access порт на Omada switch несёт:', options: ['Один untagged VLAN', 'Все VLAN tagged', 'Только WAN'], answer: 'Один untagged VLAN' },
    { question: 'Trunk к AP нужен для:', options: ['Нескольких SSID/VLAN на одном кабеле', 'Только management', 'Только PoE off'], answer: 'Нескольких SSID/VLAN на одном кабеле' },
    { question: 'Port profile позволяет:', options: ['Применить шаблон на группу портов', 'Удалить AD', 'Отключить DNS'], answer: 'Применить шаблон на группу портов' },
    { question: 'При нехватке PoE budget:', options: ['Добавить switch или midspan', 'Выключить STP', 'Удалить VLAN'], answer: 'Добавить switch или midspan' },
    { question: 'L3 firewall между VLAN на Omada обычно на:', options: ['Gateway', 'Каждом access порту', 'Принтере'], answer: 'Gateway' },
    { question: 'Loop prevention на access порту:', options: ['Предотвращает петлю от пользовательского switch', 'Ускоряет Wi‑Fi', 'Заменяет AD'], answer: 'Предотвращает петлю от пользовательского switch' },
    { question: 'PVID на trunk-порту Omada определяет:', options: ['Native (untagged) VLAN', 'Максимальную скорость порта', 'PoE класс', 'STP root priority'], answer: 'Native (untagged) VLAN' },
    { question: 'IGMP Snooping на switch нужен для:', options: ['Корректной доставки multicast (IPTV, видео)', 'DHCP relay', 'AD replication', 'VPN only'], answer: 'Корректной доставки multicast (IPTV, видео)' },
    { question: 'Port mirroring используют для:', answer: 'Копирования трафика порта на анализатор для диагностики' },
    { question: 'Storm Control на Omada switch ограничивает:', options: ['Broadcast/multicast flood на порту', 'Скорость интернета WAN', 'Количество AD-пользователей', 'DNS TTL'], answer: 'Broadcast/multicast flood на порту' },
  ],
  'omada-wireless': [
    { question: 'Corp SSID в Omada привязывается к:', options: ['VLAN / LAN network', 'Только WAN', 'Только USB'], answer: 'VLAN / LAN network' },
    { question: 'Captive portal используется для:', options: ['Guest Wi‑Fi с согласием и учётом', 'AD join', 'Печати'], answer: 'Guest Wi‑Fi с согласием и учётом' },
    { question: 'Band steering направляет клиентов на:', options: ['5 GHz', 'Только 2.4 GHz', 'Ethernet'], answer: '5 GHz' },
    { question: 'Minimum RSSI отключает:', options: ['Слабых клиентов от дальнего AP', 'Интернет полностью', 'PoE'], answer: 'Слабых клиентов от дальнего AP' },
    { question: 'RADIUS profile в Omada содержит:', options: ['IP NPS и shared secret', 'Только пароль Wi‑Fi', 'MAC всех ПК'], answer: 'IP NPS и shared secret' },
    { question: 'Mesh в Omada — когда:', options: ['Нет ethernet до AP (throughput ниже)', 'Всегда обязателен', 'Только для DC'], answer: 'Нет ethernet до AP (throughput ниже)' },
    { question: 'SSID Schedule в Omada позволяет:', options: ['Включать Wi‑Fi по расписанию', 'Автоматически менять AD-пароли', 'Отключать PoE', 'Менять VLAN на switch'], answer: 'Включать Wi‑Fi по расписанию' },
    { question: 'WPA2-PSK в корпоративной сети нежелателен потому что:', options: ['Общий пароль — сложно отозвать при увольнении', 'Не работает на 5 GHz', 'Требует FortiGate', 'Блокирует RADIUS'], answer: 'Общий пароль — сложно отозвать при увольнении', explanation: 'Enterprise 802.1X даёт per-user учётные данные.' },
    { question: 'Рекомендуемая ширина канала 5 GHz в плотном офисе:', answer: '20 или 40 MHz (80 MHz — только при малом числе соседей)' },
    { question: 'Standalone mode AP в Omada используют когда:', options: ['Нет controller — управление локально на AP', 'Обязателен для Corp SSID', 'Только для DC', 'Нужен только mesh'], answer: 'Нет controller — управление локально на AP' },
  ],
  'omada-operations': [
    { question: 'OpenVPN на Omada Gateway для:', options: ['Удалённых сотрудников', 'Только печати', 'Только AD schema'], answer: 'Удалённых сотрудников' },
    { question: 'Guest firewall policy:', options: ['Deny LAN, Allow WAN', 'Allow all', 'Deny WAN'], answer: 'Deny LAN, Allow WAN' },
    { question: 'Dual WAN failover проверяют через:', options: ['Health check ping', 'Только reboot', 'GPO'], answer: 'Health check ping' },
    { question: 'PPTP VPN:', options: ['Не использовать — небезопасен', 'Рекомендован Microsoft', 'Требуется для AD'], answer: 'Не использовать — небезопасен' },
    { question: 'Split tunnel VPN отправляет в туннель:', options: ['Только корпоративные подсети (настройка)', 'Весь трафик всегда', 'Ничего'], answer: 'Только корпоративные подсети (настройка)' },
    { question: 'При смерти controller восстанавливают из:', options: ['Backup + re-adopt', 'Только factory reset AP', 'Удаления VLAN'], answer: 'Backup + re-adopt' },
    { question: 'Syslog с Omada Gateway отправляют для:', options: ['Централизованного хранения логов', 'Ускорения Wi‑Fi', 'AD backup', 'Печати'], answer: 'Централизованного хранения логов' },
    { question: 'SNMP на Omada используют для:', options: ['Мониторинга в Zabbix/Prometheus/Grafana', 'Только DNS', 'Только GPO', 'Только печати'], answer: 'Мониторинга в Zabbix/Prometheus/Grafana' },
    { question: 'После factory reset устройства Omada нужно:', answer: 'Снова выполнить adoption и применить профили с controller' },
    { question: 'Load Balance на Dual WAN в Omada распределяет:', options: ['Сессии по обоим каналам по политике', 'Только DNS', 'Только AD replication', 'Только multicast'], answer: 'Сессии по обоим каналам по политике', explanation: 'Failover и load balance — разные режимы; проверяйте health check.' },
  ],
  'fortigate-fundamentals': [
    { question: 'FortiGate — это:', options: ['Next-Generation Firewall', 'Только Wi‑Fi controller', 'Только почтовый сервер'], answer: 'Next-Generation Firewall' },
    { question: 'VDOM в SMB обычно:', options: ['Один root', '10 обязательных', 'Не поддерживается'], answer: 'Один root' },
    { question: 'VLAN subinterface создаётся на:', options: ['Physical interface (например internal)', 'Только WAN', 'Только USB'], answer: 'Physical interface (например internal)' },
    { question: 'FortiGuard подписка даёт:', options: ['IPS, AV, Web Filter updates', 'Только GUI', 'Бесплатный интернет'], answer: 'IPS, AV, Web Filter updates' },
    { question: 'Security Fabric связывает:', options: ['FG + FortiSwitch + FortiAP', 'Только принтеры', 'Только Outlook'], answer: 'FG + FortiSwitch + FortiAP' },
    { question: 'Первое после включения нового FG:', options: ['Сменить пароль admin', 'Открыть все порты', 'Отключить DNS'], answer: 'Сменить пароль admin' },
    { question: 'FortiCare Support контракт даёт:', options: ['Доступ к обновлениям firmware и ТП', 'Бесплатный интернет', 'Автоматический AD', 'Только Wi‑Fi'], answer: 'Доступ к обновлениям firmware и ТП' },
    { question: 'Management interface FortiGate должен быть:', options: ['В защищённом VLAN с ограниченным доступом', 'На WAN с any-any', 'Без пароля', 'Только через Telnet'], answer: 'В защищённом VLAN с ограниченным доступом', explanation: 'Mgmt не должен быть доступен из интернета.' },
    { question: 'CLI-команда просмотра загрузки CPU и сессий:', answer: 'get system performance status или diagnose sys top' },
    { question: 'ZTNA (Zero Trust) на FortiGate означает:', options: ['Проверку каждого доступа по identity и контексту', 'Открытие всех портов', 'Только PSK VPN', 'Отключение логов'], answer: 'Проверку каждого доступа по identity и контексту' },
  ],
  'fortigate-firewall-policies': [
    { question: 'Firewall policy на FortiGate обрабатывается:', options: ['Сверху вниз, первое совпадение', 'Случайно', 'Снизу вверх только'], answer: 'Сверху вниз, первое совпадение' },
    { question: 'Guest VLAN policy должна:', options: ['Блокировать RFC1918, разрешать WAN', 'Разрешать всё', 'Блокировать WAN'], answer: 'Блокировать RFC1918, разрешать WAN' },
    { question: 'SNAT нужен для:', options: ['Выхода внутренних сетей в интернет', 'Печати', 'AD replication only'], answer: 'Выхода внутренних сетей в интернет' },
    { question: 'SSL Deep Inspection требует:', options: ['Corporate CA на клиентах (GPO)', 'Ничего', 'Отключения HTTPS'], answer: 'Corporate CA на клиентах (GPO)' },
    { question: 'Flow debug используют для:', options: ['Диагностики почему трафик blocked', 'Установки Windows', 'Печати'], answer: 'Диагностики почему трафик blocked' },
    { question: 'VIP на FortiGate — это:', options: ['Port forwarding / DNAT', 'VLAN ID', 'VPN user'], answer: 'Port forwarding / DNAT' },
    { question: 'Implicit deny на FortiGate означает:', options: ['Трафик без совпадения в policy блокируется', 'Всё разрешено по умолчанию', 'Только UDP блокируется', 'Guest VLAN открыт'], answer: 'Трафик без совпадения в policy блокируется' },
    { question: 'Application Control в policy позволяет:', options: ['Разрешать/блокировать по приложению, не только порту', 'Только менять DNS', 'Только AD join', 'Только печать'], answer: 'Разрешать/блокировать по приложению, не только порту' },
    { question: 'CLI для трассировки почему трафик заблокирован:', answer: 'diagnose debug flow (или diagnose firewall iprope lookup)' },
    { question: 'Log Allowed Traffic в policy нужен для:', options: ['Аудита и troubleshooting разрешённых сессий', 'Ускорения throughput', 'Отключения UTM', 'Смены VLAN'], answer: 'Аудита и troubleshooting разрешённых сессий', explanation: 'All Sessions — много логов; включайте выборочно на тестовых policy.' },
  ],
  'fortinet-vpn': [
    { question: 'SSL-VPN на FortiGate слушает часто порт:', options: ['443', '22 only', '53 only'], answer: '443' },
    { question: 'IPsec Site-to-Site для:', options: ['Офис ↔ облако/офис', 'Только печати', 'Только DHCP'], answer: 'Офис ↔ облако/офис' },
    { question: 'VPN auth в AD через:', options: ['LDAP/RADIUS', 'Только local users', 'Только PSK на клиенте'], answer: 'LDAP/RADIUS' },
    { question: 'MFA для VPN:', options: ['Обязательна в production', 'Не нужна никогда', 'Только для Guest Wi‑Fi'], answer: 'Обязательна в production' },
    { question: 'Split tunnel означает:', options: ['Часть трафика напрямую в интернет', 'Всё через VPN всегда', 'Отключение DNS'], answer: 'Часть трафика напрямую в интернет' },
    { question: 'FortiClient используется для:', options: ['SSL/IPsec VPN клиент', 'Только antivirus на FG', 'GPO editor'], answer: 'SSL/IPsec VPN клиент' },
    { question: 'IKE Phase 1 в IPsec отвечает за:', options: ['Аутентификацию и согласование шифрования туннеля', 'Только маршрутизацию', 'Только DNS', 'Только DHCP'], answer: 'Аутентификацию и согласование шифрования туннеля' },
    { question: 'SSL-VPN предпочтителен для:', options: ['Удалённых сотрудников через NAT/firewall', 'Только site-to-site', 'Только печати', 'Только AD schema'], answer: 'Удалённых сотрудников через NAT/firewall' },
    { question: 'FortiClient EMS используется для:', answer: 'Централизованного развёртывания, профилей и отчётов FortiClient' },
    { question: 'Dead Peer Detection (DPD) в IPsec нужен для:', options: ['Обнаружения обрыва туннеля и переподключения', 'Ускорения Wi‑Fi', 'Смены VLAN', 'Печати'], answer: 'Обнаружения обрыва туннеля и переподключения', explanation: 'Без DPD «мёртвый» туннель может долго не пересоздаваться.' },
  ],
  'fortinet-operations': [
    { question: 'HA Active-Passive на FortiGate даёт:', options: ['Failover при падении primary', 'Удвоение throughput всегда', 'Бесплатные лицензии'], answer: 'Failover при падении primary' },
    { question: 'FortiAnalyzer для:', options: ['Централизованных логов и отчётов', 'Только Wi‑Fi', 'Только печати'], answer: 'Централизованных логов и отчётов' },
    { question: 'FortiLink соединяет:', options: ['FortiGate и FortiSwitch', 'Только AP к интернету', 'DC к printer'], answer: 'FortiGate и FortiSwitch' },
    { question: 'Перед изменением policy на FG:', options: ['Backup конфига', 'Factory reset', 'Удалить все VLAN'], answer: 'Backup конфига' },
    { question: 'SD-WAN на FortiGate помогает с:', options: ['Multi-WAN routing по SLA', 'Только AD', 'Только GPO'], answer: 'Multi-WAN routing по SLA' },
    { question: 'CPU 100% на FG — проверить:', options: ['Session table и UTM load', 'Только кабель', 'Только DNS MX'], answer: 'Session table и UTM load' },
    { question: 'Config Revision History на FortiGate позволяет:', options: ['Откатить изменения конфигурации', 'Удалить AD', 'Сменить ISP', 'Отключить PoE'], answer: 'Откатить изменения конфигурации' },
    { question: 'Перед firmware upgrade на HA-кластере FortiGate:', options: ['Проверить совместимость версий и сделать backup', 'Сразу reboot обоих', 'Удалить все policy', 'Отключить DNS'], answer: 'Проверить совместимость версий и сделать backup', explanation: 'Обычно обновляют secondary, failover, затем primary.' },
    { question: 'Команда просмотра таблицы сессий FortiGate:', answer: 'diagnose sys session list' },
    { question: 'FortiGuard Outbreak Alerts предупреждают о:', options: ['Новых угрозах и zero-day кампаниях', 'Смене пароля AD', 'PoE budget', 'Печати'], answer: 'Новых угрозах и zero-day кампаниях' },
  ],
  'it-support-foundations': [
    { question: 'L1 support обычно решает:', options: ['Базовые инциденты и эскалирует', 'Только firewall rules', 'Только AD schema'], answer: 'Базовые инциденты и эскалирует' },
    { question: 'Incident vs Service Request:', options: ['Сломалось vs запрос услуги', 'Одно и то же', 'Только для VIP'], answer: 'Сломалось vs запрос услуги' },
    { question: 'ITSM примеры:', options: ['Jira SM, Zendesk, Freshservice', 'Только Excel', 'Только Outlook'], answer: 'Jira SM, Zendesk, Freshservice' },
    { question: 'Snipe-IT используется для:', options: ['Asset inventory', 'Firewall logs', 'VLAN design'], answer: 'Asset inventory' },
    { question: 'Путь L1 → sysadmin включает изучение:', options: ['AD, сети, PowerShell', 'Только дизайн', 'Только Kubernetes'], answer: 'AD, сети, PowerShell' },
    { question: 'Blameless в support значит:', options: ['Фокус на решении, не на обвинениях', 'Не помогать пользователю', 'Закрывать тикеты без ответа'], answer: 'Фокус на решении, не на обвинениях' },
    { question: 'CMDB отличается от asset inventory тем что:', options: ['Связывает CI и зависимости сервисов', 'Только считает мыши', 'Только DNS', 'Только VPN'], answer: 'Связывает CI и зависимости сервисов' },
    { question: 'Shift-left в IT support означает:', options: ['Раннее вовлечение IT и self-service', 'Перенос серверов влево в стойке', 'Только L3', 'Отказ от тикетов'], answer: 'Раннее вовлечение IT и self-service' },
    { question: 'В ITIL Problem отличается от Incident тем что:', answer: 'Incident — восстановить сервис сейчас; Problem — найти и устранить корневую причину' },
    { question: 'First Call Resolution (FCR) измеряет:', options: ['% решённых с первого обращения', 'Скорость интернета', 'PoE на switch', 'Количество VLAN'], answer: '% решённых с первого обращения', explanation: 'Высокий FCR снижает нагрузку на L2/L3.' },
  ],
  'helpdesk-and-sla': [
    { question: 'P1 Critical — пример:', options: ['Весь офис без интернета', 'Один user забыл пароль', 'Запрос мышки'], answer: 'Весь офис без интернета' },
    { question: 'SLA Response Time — это:', options: ['Время до первого ответа', 'Время до пенсии', 'Время доставки hardware'], answer: 'Время до первого ответа' },
    { question: 'Knowledge Base помогает:', options: ['Снизить повторяющиеся тикеты', 'Удалить AD', 'Отключить VPN'], answer: 'Снизить повторяющиеся тикеты' },
    { question: 'Эскалация должна включать:', options: ['Что уже пробовали и business impact', 'Только «не работает»', 'Ничего'], answer: 'Что уже пробовали и business impact' },
    { question: 'Reopen rate показывает:', options: ['% тикетов открытых повторно', 'Скорость интернета', 'PoE budget'], answer: '% тикетов открытых повторно' },
    { question: 'Pending (user) статус когда:', options: ['Ждём ответа пользователя', 'Проблема решена', 'P1 закрыт'], answer: 'Ждём ответа пользователя' },
    { question: 'MTTR (Mean Time To Repair) — это:', options: ['Среднее время восстановления после сбоя', 'Время до первого ответа', 'Срок лицензии', 'DHCP lease'], answer: 'Среднее время восстановления после сбоя' },
    { question: 'CSAT в helpdesk измеряет:', options: ['Удовлетворённость пользователя поддержкой', 'Скорость CPU firewall', 'Количество VLAN', 'Размер бэкапа'], answer: 'Удовлетворённость пользователя поддержкой' },
    { question: 'Минимум информации при открытии тикета:', answer: 'Пользователь, симптомы, scope (один/многие), срочность, что уже пробовали' },
    { question: 'Триаж тикетов — это:', options: ['Приоритизация по impact и urgency', 'Удаление всех P3', 'Только закрытие старых', 'Смена пароля AD'], answer: 'Приоритизация по impact и urgency', explanation: 'P1/P2 назначаются до глубокой диагностики.' },
  ],
  'endpoint-support': [
    { question: 'APIPA адрес 169.254.x.x означает:', options: ['DHCP не выдал адрес', 'Всё отлично', 'VPN active'], answer: 'DHCP не выдал адрес' },
    { question: 'BitLocker обычно через:', options: ['GPO или Intune', 'Только BIOS', 'Принтер'], answer: 'GPO или Intune' },
    { question: 'Застрявший Outlook — часто помогает:', options: ['Recreate OST / scanpst', 'Удалить AD', 'Перезагрузка switch'], answer: 'Recreate OST / scanpst' },
    { question: 'Print Spooler завис —:', options: ['Restart-Service Spooler', 'Format C:', 'Delete VLAN'], answer: 'Restart-Service Spooler' },
    { question: 'Intune Remote wipe при:', options: ['Увольнении сотрудника', 'Медленном ПК', 'Guest Wi‑Fi'], answer: 'Увольнении сотрудника' },
    { question: 'Golden image нужен для:', options: ['Стандартизации рабочих станций', 'Только серверов Linux', 'Только firewall'], answer: 'Стандартизации рабочих станций' },
    { question: 'Safe Mode with Networking запускают когда:', options: ['Нужна диагностика с сетью, но без лишних драйверов', 'Нужен только BIOS', 'Нужен только VPN', 'Нужен только принтер'], answer: 'Нужна диагностика с сетью, но без лишних драйверов' },
    { question: 'Intune (MDM) в офисе используют для:', options: ['Управления политиками и приложениями на устройствах', 'Только DNS', 'Только VLAN', 'Только печати'], answer: 'Управления политиками и приложениями на устройствах' },
    { question: 'Команда проверки применённых GPO для текущего пользователя:', answer: 'gpresult /scope user /v' },
    { question: 'Teams не запускается — часто помогает очистка:', options: ['Кэша Teams (%appdata%\\Microsoft\\Teams)', 'AD schema', 'VLAN на switch', 'DHCP scope'], answer: 'Кэша Teams (%appdata%\\Microsoft\\Teams)', explanation: 'Также проверьте WebView2 и сетевой доступ к Microsoft 365.' },
  ],
  'support-playbooks': [
    { question: 'Первый вопрос при «нет интернета»:', options: ['Только у тебя или весь офис?', 'Какой принтер?', 'Какой пароль AD?'], answer: 'Только у тебя или весь офис?' },
    { question: 'При P1 office outage L1 НЕ должен:', options: ['Перезагружать firewall без L3', 'Создать P1 тикет', 'Уведомить lead'], answer: 'Перезагружать firewall без L3' },
    { question: 'Пароль AD сбрасывают после:', options: ['Верификации личности', 'Email от неизвестного', 'Без проверки'], answer: 'Верификации личности' },
    { question: 'При ransomware на ПК:', options: ['Отключить сеть, эскалировать security', 'Продолжать работу', 'Оплатить сразу'], answer: 'Отключить сеть, эскалировать security' },
    { question: 'Leaver checklist включает:', options: ['Disable AD, revoke VPN, wipe device', 'Только delete emails', 'Только новый ноутбук'], answer: 'Disable AD, revoke VPN, wipe device' },
    { question: 'Ping 8.8.8.8 ok, но google.com fail — проблема:', options: ['DNS', 'Кабель', 'Принтер'], answer: 'DNS' },
    { question: 'Post-Incident Review (PIR) проводят чтобы:', options: ['Зафиксировать уроки и улучшить процессы', 'Найти виновного и уволить', 'Удалить все тикеты', 'Отключить VPN'], answer: 'Зафиксировать уроки и улучшить процессы' },
    { question: 'War room при P1 outage — это:', options: ['Координация ответственных в реальном времени', 'Комната с принтером', 'Guest Wi‑Fi', 'Только email переписка'], answer: 'Координация ответственных в реальном времени' },
    { question: 'Runbook onboarding нового сотрудника включает:', answer: 'Создание AD-учётки, лицензии M365, оборудование, доступы, инструктаж по безопасности' },
    { question: 'Change Request перед изменением firewall в production:', options: ['Обязателен — окно, rollback, approver', 'Не нужен никогда', 'Только для Wi‑Fi', 'Только устно'], answer: 'Обязателен — окно, rollback, approver', explanation: 'Даже «маленькое» правило может отрезать офис от AD.' },
  ],
}
